{
 "title": "UI_service_monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Buisness_Logic_monitoring",
   "type": "graph",
   "description": "counts posts and comments  rate",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(post_count[1h])" },
    { "expr": "rate(comment_count[1h])" }
   ]
  },
  {
   "title": "http response time stats",
   "type": "graph",
   "description": "http response time stats - how long does the visitor wait for response",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Rate of HTTP requests with error",
   "type": "graph",
   "description": "Add HTTP requests with error status code",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "UI HTTP Requests",
   "type": "graph",
   "description": "All HTTP requests that UI service receives",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(ui_request_count[3m])" }
   ]
  }
 ]
}